### PR TITLE
Fix FMV Colors (but not artifacting)

### PR DESCRIPTION
**Pull request by deanff**
#1309 

Dropbox Screenshots: https://www.dropbox.com/sh/lzkj0hxnbeuidkd/AACoSzslWPUzO3BHG1hTKQQla?dl=0

Turn monitor brightness up to view the artifacting (left side of screen)

Fourth image has brightness increased by 4 to try and match the OG, but artifacting still remains...

### CODE REVIEW

**Comment by paulsapps** [comment]
artifacting? I guess AE hasn't got the colors issue either?

**Comment by deanff** [comment]
Maybe artifacting is the wrong word? There is some kind of pixelation present in the FMVs (particularly in dark areas) that was not present in the original files. Same goes for AE. 

Dark gradients seem to suffer most... compare the left pillar in the following images:
https://www.dropbox.com/sh/lzkj0hxnbeuidkd/AACoSzslWPUzO3BHG1hTKQQla?dl=0

Or turn up monitor brightness and view the left/right sides of Oddworld Inhabitants logo FMV.

**Comment by paulsapps** [comment]
Is that not just the screen filtering the OG has?

**Comment by paulsapps** [comment]
if its not its prob worth raising another issue for it and we'll close #1309 with this?

**Comment by deanff** [comment]
Hard to say - because I cannot play FMVs in the OG PC release.
I can say, however, that the video I created by converting AO DDVs to STR then lossly converting them to MP4 (1280x960 - nearest neighbor) is better quality than what plays in relive. 
None of this flickering pixelation and gradients looks a lot better...

**Pull request merged**
