### PR TITLE
FMV Audio Fix

### PR DESCRIPTION
**Pull request by deanff**

### CODE REVIEW

**Comment by paulsapps** [comment]
does this not de-sync then? it seems to be tied to real time rather than the audio clock?

**Comment by deanff** [comment]
Haven't had issues. There is one thing that's a bit different though... If you grab the window and move it around, the game will get in a temporary audio loop until you let go. AE does this as well. What's different is AO will catch up! Whether this is an issue - I'm unsure, was kinda hoping that we could somehow fix the whole temp audio loop thing and just have normal playback when dragging the window.

**Comment by paulsapps** [comment]
Should we remove the code that disables the FMVs if they now work then?

**Comment by deanff** [comment]
I think so... The only remaining (minor) issue that springs to mind is the colours - the ends of FMVs and the start of Gameplay / the main menu don't always match up, and vice versa.

**Comment by paulsapps** [comment]
I think that is an OG issue

**Comment by deanff** [comment]
Yeah - I think you're right. PS1 has matching colors, but OG PC port does not.

**Comment by paulsapps** [comment]
You gonna remove the if 0 then?

**Comment by deanff** [comment]
Which if 0? I've removed the #if 1 with the comment "Don't play FMVs for now till sound issues are fixed"

**Comment by paulsapps** [comment]
ah yes, I am the blind mud

**Comment by paulsapps** [comment]
So after some testing I do see one bug, the audio isn't stopped so you can hear music at the same time

**Pull request merged**
